version: 2
jobs:
  lint:
    docker: &py37
      - image: playpauseandstop/docker-python:1.1.0-py37
    steps:
      - checkout
      - run: make install
      - run: make ci-lint

  test35:
    docker:
      - image: playpauseandstop/docker-python:1.1.0-py35
    steps:
      - checkout
      - run: mkdir -p test-results/pytest
      - run: make install
      - run: PYTEST_ADDOPTS=--junitxml=test-results/pytest/junit.xml TOXENV=py35 make ci-test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  test36:
    docker:
      - image: playpauseandstop/docker-python:1.1.0-py36
    steps:
      - checkout
      - run: mkdir -p test-results/pytest
      - run: make install
      - run: PYTEST_ADDOPTS=--junitxml=test-results/pytest/junit.xml TOXENV=py36 make ci-test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  test37:
    docker: *py37
    steps:
      - checkout
      - run: mkdir -p test-results/pytest
      - run: make install
      - run: PYTEST_ADDOPTS=--junitxml=test-results/pytest/junit.xml TOXENV=py37 make ci-test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - run: make coveralls

  deploy:
    docker: *py37
    steps:
      - checkout
      - run: make install
      - run: make ci-deploy

workflows:
  version: 2
  ci:
    jobs:
      - lint:
          filters: &all_tags_and_branches
            tags:
              only: /.*/

      - test35:
          requires:
            - lint
          filters: *all_tags_and_branches

      - test36:
          requires:
            - lint
          filters: *all_tags_and_branches

      - test37:
          requires:
            - lint
          filters: *all_tags_and_branches

      - deploy:
          requires:
            - test35
            - test36
            - test37
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
