version: 2
jobs:
  lint:
    docker: &py37
      - image: playpauseandstop/docker-python:2.0.0-py37
    steps:
      - checkout
      - run: make install
      - run: make lint-ci

  test36:
    docker:
      - image: playpauseandstop/docker-python:2.0.0-py36
    steps:
      - checkout
      - run: mkdir -p test-results/pytest
      - run: make install
      - run: PYTEST_ADDOPTS=--junitxml=test-results/pytest/junit.xml TOXENV=py36 make test-ci
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  test37:
    docker: *py37
    steps:
      - checkout
      - run: mkdir -p test-results/pytest
      - run: make install
      - run: PYTEST_ADDOPTS=--junitxml=test-results/pytest/junit.xml TOXENV=py37 make test-ci
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - run: make coveralls

  test38:
    docker:
      - image: python/3.8.0-slim-stretch
    steps:
      - checkout
      - run: POETRY_PREVIEW=1 curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      - run: python -m pip install tox
      - run: mkdir -p test-results/pytest
      - run: POETRY=${HOME}/.poetry/bin/poetry PYTEST_ADDOPTS=--junitxml=test-results/pytest/junit.xml TOXENV=py38 make test-ci
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  deploy:
    docker: *py37
    steps:
      - checkout
      - run: make install
      - run: make deploy-ci

workflows:
  version: 2
  ci:
    jobs:
      - lint:
          filters: &all_tags_and_branches
            tags:
              only: /.*/

      - test36:
          requires:
            - lint
          filters: *all_tags_and_branches

      - test37:
          requires:
            - lint
          filters: *all_tags_and_branches

      - test38:
          requires:
            - lint
          filters: *all_tags_and_branches

      - deploy:
          requires:
            - test36
            - test37
            - test38
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
